spring.application.name=KinoStats

spring.datasource.url=jdbc:postgresql://localhost:5432/KinoStatsDBTest
spring.datasource.username=postgres
spring.datasource.password=CydYn6%^u**4**m
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tmdb.api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNzhkNjIxYzBhNmRlNDFhNTE3MGQ1NmM0ZDVmZTE2ZSIsIm5iZiI6MTc3NjIwOTk1My41ODA5OTk5LCJzdWIiOiI2OWRlZDAyMTRiYjk5OGYxYTNiNGM2NmIiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.lcM1lKGKI3ueJOcUCbpAHu8ddKKDU3Vz_92vQZy5VcA
tmdb.api.base-url=https://api.themoviedb.org/3

sendgrid.api-key=
sendgrid.from-email=kinostats9@gmail.com