spring.application.name=KinoStats

spring.datasource.url=jdbc:postgresql://localhost:5432/KinoStatsDBTest
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tmdb.api.key=
tmdb.api.base-url=https://api.themoviedb.org/3

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sendgrid.api-key=
sendgrid.from-email=